# Generated by Django 2.0 on 2018-04-18 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClickEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('click_url', models.CharField(max_length=200)),
                ('uuid', models.CharField(max_length=200)),
                ('time', models.CharField(max_length=200)),
                ('epoch', models.FloatField()),
                ('endpoint', models.CharField(max_length=200)),
            ],
        ),
    ]
